name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bun Build 
        uses: oven-sh/setup-bun@v1
      - run: |
          bun init
          bun install
      - run: bun run build
        env: 
          VITE_STATIC_PATH: ${{ secrets.VITE_STATIC_PATH }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: paopao-inc-site
          path: dist
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment